variables:
  PROJECT_NAME: vshn-try-syn-tools
  OC_IMAGE: docker.io/appuio/oc:v4.9
  APPUIO_CLOUD_REGISTRY: registry.cloudscale-lpg-2.appuio.cloud
  TRY_SYN_MAIN_IMAGE: ${APPUIO_CLOUD_REGISTRY}/vshn-try-syn-tools/vshn-try-syn-tools:latest

stages:
  - build
  - deploy

.build-docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  tags:
    - dockerbuild
  script:
    - docker login -u gitlab-ci -p ${APPUIO_CLOUD_REGISTRY_TOKEN} ${APPUIO_CLOUD_REGISTRY}
    - docker pull $TRY_SYN_MAIN_IMAGE || true
    - docker build --cache-from $TRY_SYN_MAIN_IMAGE -t $TRY_SYN_MAIN_IMAGE -f deployment/Dockerfile .
    - if [ ${CI_COMMIT_REF_NAME} == "master" ]; then docker push $TRY_SYN_MAIN_IMAGE; fi

master:build:
  extends: .build-docker
  only:
    - master

master:deploy:
  stage: deploy
  image: $OC_IMAGE
  environment:
    name: production
    url: https://try.syn.tools
  script:
    - oc -n ${PROJECT_NAME} apply -f deployment/try-syn-tools.yaml
    - oc -n ${PROJECT_NAME} rollout latest dc/vshn-try-syn-tools
  only:
    - master
