apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: vshn-try-syn-tools
spec:
  rules:
  - host: try.syn.tools
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vshn-try-syn-tools
            port:
              number: 8080
  tls:
  - hosts:
    - try.syn.tools
    secretName: vshn-try-syn-tools-cert
---
apiVersion: v1
kind: Service
metadata:
  name: vshn-try-syn-tools
  labels:
    app: vshn-try-syn-tools
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vshn-try-syn-tools
  type: ClusterIP
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: vshn-try-syn-tools
  labels:
    app: vshn-try-syn-tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vshn-try-syn-tools
    spec:
      containers:
        - name: main
          image: registry.cloudscale-lpg-2.appuio.cloud/vshn-docs/vshn-try-syn-tools:latest
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
            periodSeconds: 60
            initialDelaySeconds: 5
          ports:
          - containerPort: 8080
